### ISSUE TITLE
test_event_prior() failed

### ISSUE THREAD

**Issue by ljwharbers** [cbg-ethz/SCICoNE#100]
Hi,

I cloned into the repository and after building I tried to run ./tests to check if everything went successful. However the test `test_event_prior()` failed and I'm unsure if I overlooked something or there might be a bug. See here the stdout:

> UNIT TESTS
> xxhash validation test passed!
> Reading the input matrix...
> Input matrix is read.
> Method of moments estimated nu=0.980538
> n_regions: 1
> Combining scores...
> Done.
> Breakpoint detection validation test passed!
> Tree prior validation test passed!
> tests: /home/xxxx/SCICoNE/tests/validation.h:657: void test_event_prior(): Assertion `abs(event_prior - event_prior_gt) <= epsilon' failed.
> Aborted

Thanks,
Luuk

**Comment by pedrofale** [comment]
Dear Luuk,

Thank you for pointing this out! We had forgotten to push a few changes, so the issue was on our side. Indeed, if you check the badges in the README, the build was failing. [It is fixed now](https://github.com/cbg-ethz/SCICoNE). If you clone the repository now and install SCICoNE, the tests will pass and you are ready to go! We recommend that you start with the tutorial: https://github.com/cbg-ethz/SCICoNE/blob/master/notebooks/tutorial.ipynb. 

Thanks your interest in SCICoNE.
Pedro
