### ISSUE TITLE
How to use SCICoNE on 10X mouse data?

### ISSUE THREAD

**Issue by Suzuk1** [cbg-ethz/SCICoNE#116]
Hi,

Thank you for developing SCICoNE!
I tried to run SCICoNE on 10x Genomics mouse data following the tutorial, but I received some error messages.
<img width="896" alt="スクリーンショット 2021-07-28 14 49 43" src="https://user-images.githubusercontent.com/19612536/128374835-34828f29-f42a-4386-83a6-10877c9f88a6.png">
This error is caused by the int-tye Variable. Mouse 10X hdf5 data contains chromosome data as “chr1”, “chr2”,…,”chrX”, and ”chrY”. So I changed the python codes(/python3.6/dist-packages/scicone/utils.py, utils _10x.py)

**In utils.py code**
<img width="968" alt="スクリーンショット 2021-07-28 18 50 13" src="https://user-images.githubusercontent.com/19612536/128374940-59816d07-8262-4adc-80f0-36c3d4356d57.png">

**In utils_10x.py code**
I changed form [ch] to [str("chr"+ch)] like as follows.
````
def merge_data_by_chromosome(h5f, key="normalized_counts", 
….
        #for human
        #mat = h5f[key][ch][:][0:n_cells]
        #for mouse
        mat = h5f[key][str("chr"+ch)][:][0:n_cells]
````

 and sci.read_10x() works. But other error occurrs.

<img width="890" alt="スクリーンショット 2021-07-28 18 24 01" src="https://user-images.githubusercontent.com/19612536/128374737-37eb5bef-d1e4-46d7-afb1-f5e6700ea7ed.png">

Could you tell me how to treat mouse data on SCICoNE?

**Comment by pedrofale** [comment]
Hi @Suzuk1,

Thanks for your message! Indeed SCICoNE assumes there are 23 chromosomes, so it throws that error for mouse data since they have fewer than that. We should make this more flexible.

However, while that functionality is not available, please note that only the Python wrapper has that limitation. You can do your own pre-processing of the 10X data and use it as input to the [C++ program](https://github.com/cbg-ethz/SCICoNE/blob/master/scicone/reference.md), which is much more flexible.

**Comment by Suzuk1** [comment]
I appreciate your help. I will try to use the C++ program and looking forward to seeing a more flexible SCiCoNE version!
